<?php

/**
 * @file
 * Provides formatter settings for limiting the number of values to display on
 * multi-value fields.
 *
 * Based on Field Delimiter module (http://drupal.org/project/field_delimiter).
 */

define('FIELD_MULTIPLE_LIMIT_ALL', -1);

/**
 * Implements hook_field_formatter_info_alter().
 */
function field_multiple_limit_field_formatter_info_alter(&$info) {
  // Added to all formatters.
  foreach ($info as $formatter_key => &$formatter) {
    $formatter['settings']['field_multiple_limit'] = FIELD_MULTIPLE_LIMIT_ALL;
    $formatter['settings']['field_multiple_limit_offset'] = 0;
  }
}

/**
 * Implements hook_field_formatter_settings_summary_alter().
 */
function field_multiple_limit_field_formatter_settings_summary_alter(&$summary, $context) {
  if (!empty($context['field']['cardinality']) && ($context['field']['cardinality'] > 1 || $context['field']['cardinality'] == FIELD_CARDINALITY_UNLIMITED)) {
    $settings = $context['instance']['display'][$context['view_mode']]['settings'];

    if (!empty($summary)) {
      $summary .= '<br />';
    }

    if (!empty($settings['field_multiple_limit']) && $settings['field_multiple_limit'] != FIELD_MULTIPLE_LIMIT_ALL) {
      $summary .= t('Displaying @limit values', array('@limit' => $settings['field_multiple_limit']));
    }
    else {
      $summary .= t('Displaying all values');
    }

    if (!empty($settings['field_multiple_limit_offset'])) {
      $summary .= '<br />' . t('Skipping the first @offset values', array('@offset' => $settings['field_multiple_limit_offset']));
    }
  }
}

/**
 * Implements hook_field_formatter_settings_form_alter().
 */
function field_multiple_limit_field_formatter_settings_form_alter(&$settings_form, $context) {
  // Do not display the module settings in views, as Backdrop core Views already
  // supports setting values to display, and also offset (via the "Multiple
  // field settings" fieldset).
  if ($context['instance']['entity_type'] != 'views') {
    if (!empty($context['field']['cardinality']) && ($context['field']['cardinality'] > 1 || $context['field']['cardinality'] ==   FIELD_CARDINALITY_UNLIMITED)) {
      $settings = $context['instance']['display'][$context['view_mode']]['settings'];
  
      $settings_form['field_multiple_limit'] = array(
        '#type' => 'select',
        '#title' => t('Number of values to display'),
        '#options' => array(FIELD_MULTIPLE_LIMIT_ALL => t('All')) + backdrop_map_assoc(range(1, 10)),
        '#default_value' => $settings['field_multiple_limit'],
      );
  
      $settings_form['field_multiple_limit_offset'] = array(
        '#type' => 'select',
        '#title' => t('Number of values to skip'),
        '#options' => backdrop_map_assoc(range(0, 10)),
        '#default_value' => $settings['field_multiple_limit_offset'],
      );
    }
  }
}
